service: SheScreen
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10
  iam:
    role: null  # If you have a custom role, specify it here
    permissionsBoundary: null  # If you have a permissions boundary, specify it here
    deploymentRole:
      name: null  # If you have a CloudFormation deployment role, specify it here
    
      statements:
        - Effect: "Allow"
          Action:
            - "ssm:GetParameter"
          Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:*

        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: !Sub arn:aws:secretsmanager:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:secret:authSecrets-FPE1gD
      managedPolicies:  # If you have managed policies, specify them here
        - arn:aws:iam::aws:policy/YourManagedPolicy

# Other provider settings can be added here

      # beside authSecrets what is the number/letter combo?

# httpApi:
#     cors:
#       allowedOrigins:
#         -
#       allowedHeaders:
#         -
#       allowedMethods:
#         -
#     authorizers:
#       customAuthorizer:
#         type: request
#         functionName: #insert name of function we create#

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  login:
    handler: handlers.login.login
    events:
      - httpApi:
          path: /login
          method: post

  createScreening:
    handler: handlers.cancer_screening.create_screening
    events:
      - httpApi:
          path: /screening
          method: post

  getHistory:
    handler: handlers.cancer_screening.get_history
    events:
      - httpApi:
          path: /screening/{id}
          method: get

# functions:

#   logout:
#     handler: handlers.logout.handler
#     events:
#       - httpApi:
#           path: /logout
#           method: post
#   acctCreate:
#     handler: handlers.logout.handler
#     events:
#       - httpApi:
#           path: /create
#           method: post
#   acctgetbyId:
#     handler: handlers.getbyId.handler
#     events:
#       - httpApi:
#           path: /Id
#           method: post
#   acctupdate:
#     handler: handlers.update.handler
#     events:
#       - httpApi:
#           path: /update
#           method: post
#   acctdelete:
#     handler: handlers.delete.handler
#     events:
#       - httpApi:
#           path: /delete
#           method: post
#   acctget:
#     handler: handlers.get.handler
#     events:
#       - httpApi:
#           path: /get
#           method: post

#   authorizerFunc:
#     handler: authorizer.lambda_handler

plugins:
  - serverless-python-requirements
