service: SheScreen
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10


# httpApi:
#     cors: 
#       allowedOrigins:
#         - 
#       allowedHeaders:
#         - 
#       allowedMethods:
#         - 
#     authorizers:
#       customAuthorizer:
#         type: request
#         functionName: #insert name of function we create#


functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  login:
    handler: handlers.login.handler
    events:
      - httpApi:
          path: /login
          method: post


# functions:

#   logout:
#     handler: handlers.logout.handler
#     events:
#       - httpApi:
#           path: /logout
#           method: post
#   acctCreate:
#     handler: handlers.logout.handler
#     events:
#       - httpApi:
#           path: /create
#           method: post
#   acctgetbyId:
#     handler: handlers.getbyId.handler
#     events:
#       - httpApi:
#           path: /Id
#           method: post
#   acctupdate:
#     handler: handlers.update.handler
#     events:
#       - httpApi:
#           path: /update
#           method: post
#   acctdelete:
#     handler: handlers.delete.handler
#     events:
#       - httpApi:
#           path: /delete
#           method: post
#   acctget:
#     handler: handlers.get.handler
#     events:
#       - httpApi:
#           path: /get
#           method: post

#   authorizerFunc:
#     handler: authorizer.lambda_handler

plugins:
  - serverless-python-requirements
